# -*- coding: utf-8 -*-
"""whitby_covid_tracing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1585yBw8-Jo40HPnaJSmAPlhhBsT-0epC
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Extract data
infections = props_df['Infections'].dropna()
traces = props_df['Traces'].dropna()

# Determine bin edges manually to avoid issues with binwidth
min_val = min(infections.min(), traces.min())
max_val = max(infections.max(), traces.max())

# Handle edge case where all values are the same
if min_val == max_val:
    min_val -= 0.025
    max_val += 0.025

# Create shared bin edges
bin_edges = np.linspace(min_val, max_val, 21)  # 20 bins

# Plotting
plt.figure(figsize=(10, 6))

sns.histplot(infections, bins=bin_edges, color="blue", alpha=0.75, kde=False, label='Infections from Weddings')
sns.histplot(traces, bins=bin_edges, color="red", alpha=0.75, kde=False, label='Traced to Weddings')

plt.xlabel("Proportion of cases")
plt.ylabel("Frequency")
plt.title("Impact of Contact Tracing on Perceived Infection Sources")
plt.legend()
plt.tight_layout()
plt.show()